cuboid:
  floor:
    dims: [2.5, 2.5, 0.2] # x, y, z
    pose: [0.0, 0.0, -0.1, 0, 0, 0, 1.0] # x, y, z, qx, qy, qz, qw
    color: [0.6, 0.6, 0.8, 1.0]
  toy_box_w1: # Front: Height = 0.2 + 0.3
    dims: [0.82, 0.1, 0.6] # x, y, z
    pose: [0.54, -0.16, 0.2, 0.99938, 0.0, 0.0, 0.03533] # x, y, z, qw, qx, qy, qz
    color: [1.0, 0.0, 0.0, 1.0]
  toy_box_w2: # Back: Height = 0.25 + 0.325
    dims: [1.0, 0.1, 0.65] # x, y, z
    pose: [0.54, -0.6, 0.25, 0.99938, 0.0, 0.0, 0.03533] # x, y, z, qw, qx, qy, qz
    color: [0.0, 0.0, 1.0, 1.0]
  toy_box_w3: # Side: Height = 0.2 + 0.3
    dims: [1.0, 0.1, 0.6] # x, y, z
    pose: [0.11, -0.68, 0.2, 0.70711, 0.0, 0.0, 0.70711] # x, y, z, qw, qx, qy, qz
    color: [0.0, 0.0, 1.0, 1.0]
