name: Format

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Whenever certain branches are pushed
  push:
    branches: [main]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  action-ros-lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-lint@0.1.4
        with:
          linter: ${{ matrix.linter }}
          package-name: grab2_behavior_tree grab2_controller grab2_interfaces grab2_planner
